#define DELAY_US    20000
#define BIT(n) (0x01<<(n))
#define KB_IRQ 1
#define KBC_STATUS 0x64
#define KBC_COMMAND 0x64
#define KBC_OUT_BUF 0x60
#define KBC_IN_BUF 0x60
#define KBC_INBUF_FULL BIT(1)
#define KBC_OUTBUF_FULL BIT(0)
#define KBC_STAT_PARITY BIT(7)
#define KBC_STAT_TIMEOUT BIT(6)
#define KB_2BYTE_SCODE 0xE0
#define KB_LED_CMD 0xED
#define ACK 0xFA
#define RESEND 0xFE
#define ERROR 0xFC
#define MOUSE_IRQ 12
#define KBC_ENABLE_MOUSE 0xA8
#define WRITE_TO_MOUSE 0xD4
#define MOUSE_STATUS_REQUEST 0xE9
#define ENABLE_DATA_PACKETS 0xF4
